version: "3"

networks:
  gift-box.net:
    driver: bridge

services:
  sql:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_USER}
    ports:
      - "0909:3306"
    networks:
      gift-box.net:
        aliases:
            - sql.db




  adminer:
    image: adminer
    ports:
      - "1010:8080"
    networks:
      - gift-box.net
    depends_on:
      - sql

  php:
    image: canals/php:latest
    ports:
      - "5280:80"
    volumes :
      - ./gift.appli/public:/var/www/html
      - ./shared/img:/var/www/html/img
      - ./gift.appli/src:/var/www/src
      - ./gift.appli/test:/var/www/test
    working_dir: /var/www/src
    networks:
      - gift-box.net
    depends_on:
      - sql

  api:
    image: canals/php:latest
    ports:
      - "5380:80"
    volumes:
      - ./gift.api/public:/var/www/html
      - ./gift.api/src:/var/www/src
      - ./shared/img:/var/www/html/img
    working_dir: /var/www/src
    networks:
      - gift-box.net
    depends_on:
      - sql